depts = {
    "Bakery":{
        "subcategories":[],
        "brands":[],
        "items":{}
    },
    "Breakfast":{
        "subcategories":[],
        "brands":[],
        "items":{}
    },
    "Beauty":{
        "subcategories":[],
        "brands":[],
        "items":{}
    },
    "Fresh":{
        "subcategories":[],
        "brands":[],
        "items":{}
    },
    "Frozen":{
        "subcategories":[],
        "brands":[],
        "items":{}
    },
    "GM-Household":{
        "subcategories":[],
        "brands":[],
        "items":{}
    },
    "Home Office":{
        "subcategories":[],
        "brands":[],
        "items":{}
    },
    "Health":{
        "subcategories":[],
        "brands":[],
        "items":{}
    }
}
items = {
}